name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d0b'
    - '#443a21'
    - '#f2fafd'
    - '#898778'
    - '#b9b899'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: 8cae7172-cce6-4296-8466-833301940860
    url: null
